[project]
name = "diffusion-experiments"
version = "0.1.0"
description = "A collection of experiments with diffusion models."
requires-python = ">=3.11.0, <3.12"
dependencies = [
    "autocvd",
    "astropy",
    "amici==0.34.2",
    "black",
    "bayesflow==2.0.12",
    "chainconsumer",
    "corner",
    "colorcet>=3.1.0",
    "fides==0.8.0",
    "fyeldgenerator>=0.1.7",
    "hydra-core==1.3",
    "galpy",
    "galstreams",
    "gpustat",
    "ipython",
    "ipykernel",
    "jax[cuda]==0.7.1",
    "joblib==1.5.2",
    "keras>=3.10",
    "marimo",
    "matplotlib",
    "numba>=0.63.1",
    "numpy>=1.26.4",
    "optuna",
    "scipy>=1.12.0",
    "tensorflow==2.20.0",
    "torch==2.9.1",
    "tqdm==4.67.1",
    "plotly>=6.5.2",
    "pyzmq>=27.1.0",
    "StreaMax",
    "scikit-learn",
    "tarp",
    "deprecation",
]


[tool.uv.sources]
sbibm = { git = "https://github.com/arrjon/sbibm.git", rev = "dev" }
galstreams = {git = "https://github.com/cmateu/galstreams"}
galpy = {git = "https://github.com/jobovy/galpy.git"}
StreaMax = {path = "/export/home/vgiusepp/StreaMAX", editable = true}

