base_dir: "/export/home/vgiusepp/diffusion-experiments/case_study5/project_stream/data/"
data_dir: "streams/data_multistream_gala_new/"
model_dir: "models/gala6D/new_hyper/model54_60k_1000epochs"
# model_dir: "models/streamax_new/normal_mask/modeltest_100k_1000epochs"
multistream_n_simulation: 100
# results_dir: "plots/streamax_new/normal_mask/modeltest_100k_1000epochs/100test"
results_dir: "plots/gala6D/new_hyper/model54_60k_1000epochs/nocomposition_100test_new"
# results_dir: "hyperparameter_tuning/gala/random_obswindows/300k/model_25/100test"
use_streamax_simulator: False

#training hyperparameters
n_samples: 1000
method: "two_step_adaptive"
steps: "adaptive"
max_steps: 1000
mini_batch_size: null
batch_size: 30
inverse_compositional_bridge_d1: 7
noise_schedule: null
# noise_schedule: 
  # min_log_snr: -15
  # max_log_snr: 15
  # shift: 5.0
  # weighting: "likelihood_weighting"
verbose: 2

#nmes of parameters
sim_data: "sim_data_projected"
inference_conditions:
  - "j"
parameters_global:
- m_Triaxial_halo
- r_Triaxial_halo
- q2_Triaxial_halo
- rho_thin_disk
- hr_thin_disk
- hz_thin_disk
- rho_thick_disk
- hr_thick_disk
- hz_thick_disk
# - m_Triaxial_rotated_halo
# - r_Triaxial_rotated_halo
# - dirx_Triaxial_rotated_halo
# - diry_Triaxial_rotated_halo
# - dirz_Triaxial_rotated_halo


parameters_local:
- m_progenitor
- a_progenitor
- vr
- r
- mu_ra_cosdec
- mu_dec
paramater_global_pretty:
  - "$M_{NFW}$"
  - "$r_{NFW}$"
  - "$q_{NFW}$"
  - "$\\rho_t$"
  - "$h_t$"
  - "$z_t$"
  - "$\\rho_k$"
  - "$h_k$"
  - "$z_k$"
  # - "$M_{NFW}$"
  # - "$r_{NFW}$"
  # - "$dirx_{NFW}$"
  # - "$diry_{NFW}$"
  # - "$dirz_{NFW}$"


parameter_local_pretty:
- $M_{prog}$
- $a_{prog}$
- $v_r$
- $r$
- $\mu_{\alpha*}$
- $\mu_{\delta}$
#Augmentations
target_streams:
  Pal5: 0 #this is the j index
  NGC3201: 1
  M68: 2

# observational_window:
#   Pal5:
#     ra_min: 220.98008280733634
#     # ra_max: 245.89465019770668
#     ra_max: 250.0
#     # dec_min: -10.644267714585839
#     dec_min: -13.0
#     # dec_max: 9.279576254116762
#     dec_max: 10.0
#   NGC3201:
#     ra_min: 42.29847920913508
#     # ra_max: 178.36142433209437
#     ra_max: 140.0
#     dec_min: -47.79545565626234
#     dec_max: 20.812029301121846
#   M68:
#     ra_min: 189.73694638139526
#     # ra_max: 273.48942253688114
#     ra_max: 280.0
#     dec_min: -47.32109546202406
#     # dec_max: 66.52056055901161
#     dec_max: 70.0

# observational_window:
#   Pal5:
#     ra_min: 220.98008280733634
#     ra_max: 245.89465019770668
#     dec_min: -10.644267714585839
#     dec_max: 9.279576254116762
#   NGC3201:
#     ra_min: 42.29847920913508
#     ra_max: 140.0
#     dec_min: -47.79545565626234
#     dec_max: 20.812029301121846
#   M68:
#     ra_min: 189.73694638139526
#     ra_max: 273.48942253688114
#     dec_min: -47.32109546202406
#     dec_max: 66.52056055901161

# ploting 
observational_window: 
  Pal5:
    ra_min: 220.98008280733634
    ra_max: 245.89465019770668
    dec_min: -10.644267714585839
    dec_max: 9.279576254116762
  NGC3201:
    ra_min: 42.29847920913508
    ra_max: 125.0
    dec_min: -35.79545565626234
    dec_max: 20.812029301121846
  M68:
    ra_min: 189.73694638139526
    ra_max: 273.48942253688114
    dec_min: -20.0
    dec_max: 66.52056055901161

observed_n_stars:
  Pal5: 129
  # NGC3201: 607
  NGC3201: 195
  M68: 297

gaia_id:
  Pal5: "Pal-5"
  NGC3201: "Gjoll"
  M68: "Fjorm"

min_star_with_vlos:
  Pal5: 69
  # NGC3201: 40
  NGC3201: 37
  M68: 29

masked_value_vlos:
  Pal5:
    mean: -51.76
    std: 137.04
  NGC3201:
    mean: 479.98
    std: 71.38
  M68:
    mean: -95.42
    std: 65.70

augmentations:
- "cut_to_300_particles"
# - "remove_los_velocity"
- convert_distance_to_parallax
- observational_window
# - observational_window_random
- observed_n_stars
- mask_vlos
- sample_magnitudes
- sample_obs_error
- apply_obs_error
# - flip_dirz
- concatentate_sigma_error_to_sim_data
- concatenate_magnitudes_to_sim_data
- concatenate_vlos_mask_to_sim_data
- concatenate_j_to_sim_data

# error_keys: null #default is ["ra", "dec", "parallax", "mu_ra", "mu_dec"]
error_keys:
- ra
- dec
- parallax
- mu_ra
- mu_dec
- v_los

#global model network:
global_model:
  dropout: 0.1
  summary_dim: 77
  embed_dims: 105
  num_heads: 7
  mlp_depths: 5
  mlp_widths: 121
  inference_mlp_depth: 7
  inference_mlp_width: 208
  inference_time_embedding_dim: 58

#local model network:
local_model:
  dropout: 0.1
  summary_dim: 16

hydra:
  run:
    dir: ${base_dir}/${results_dir}
