base_dir: "/export/home/vgiusepp/diffusion-experiments/case_study5/project_stream/data/"
data_dir: "streams/data_multistream_streamax/"
model_dir: "models/local_models/model_local_new_streamax_concatenation_500_hyper/"
multistream_n_simulation: 333
results_dir: "plots/plots_local/plots_local_new_streamax_concatenation_500_hyper_333tests/"
use_streamax_simulator: True

#training hyperparameters
n_samples: 1_000
method: "two_step_adaptive"
steps: "adaptive"
max_steps: 1000
mini_batch_size: null
batch_size: 10
inverse_compositional_bridge_d1: 6
noise_schedule: null
  # min_log_snr: -15
  # max_log_snr: 15
  # shift: 10
  # weighting: "sigmoid"
verbose: 2

#nmes of parameters
sim_data: "sim_data_projected"
inference_conditions:
  - "j"
parameters_global:
  - "m_Triaxial_rotated_halo"
  - "r_Triaxial_rotated_halo"
  - "dirx_Triaxial_rotated_halo"
  - "diry_Triaxial_rotated_halo"
  - "dirz_Triaxial_rotated_halo"
  - "m_disk_MW2014"
  - "r_disk_MW2014"
  - "m_bulge"
parameters_local:
  # - "m_progenitor"
  # - "a_progenitor"
  - "vr"
  - "r"
  - "mu_ra_cosdec"
  - "mu_dec"
#names for printing
paramater_global_pretty:
  - "$M_{NFW}$"
  - "$r_{NFW}$"
  - "$\\hat{x}_{NFW}$"
  - "$\\hat{y}_{NFW}$"
  - "$\\hat{z}_{NFW}$"
  - "$M_{MN}$"
  - "$r_{MN}$"
  - "$M_{bulge}$"

parameter_local_pretty:
  # - "$M_{prog}$"
  # - "$a_{prog}$"
  - "$v_r$"
  - "$r$"
  - "$\\mu_{\\alpha*}$"
  - "$\\mu_{\\delta}$"

#Augmentations
target_streams:
  Pal5: 0 #this is the j index
  NGC3201: 1
  M68: 2

observational_window:
  Pal5:
    ra_min: 220.98008280733634
    ra_max: 245.89465019770668
    dec_min: -10.644267714585839
    dec_max: 9.279576254116762
  NGC3201:
    ra_min: 42.29847920913508
    ra_max: 178.36142433209437
    dec_min: -47.79545565626234
    dec_max: 20.812029301121846
  M68:
    ra_min: 189.73694638139526
    ra_max: 273.48942253688114
    dec_min: -47.32109546202406
    dec_max: 66.52056055901161

observed_n_stars:
  Pal5: 129
  NGC3201: 607
  M68: 297

min_star_with_vlos:
  Pal5: 69
  NGC3201: 40
  M68: 29

error_keys: null #default is ["ra", "dec", "parallax", "mu_ra", "mu_dec"]
# error_keys: 
#   - "ra"
#   - "dec"
#   - "parallax"
#   - "mu_ra"
#   - "mu_dec"
#   - "v_los" #override default error keys

masked_value_vlos:
  Pal5:
    mean: -51.76
    std: 137.04
  NGC3201:
    mean: 479.98
    std: 71.38
  M68:
    mean: -95.42
    std: 65.70


gaia_id:
  Pal5: "Pal-5"
  NGC3201: "Gjoll"
  M68: "Fjorm"

augmentations:
  - "remove_los_velocity"
  - "convert_distance_to_parallax"
  - "observational_window"
  - "observed_n_stars"
  - "sample_magnitudes"
  - "sample_obs_error"
  - "apply_obs_error"
  - "flip_dirz"
  - "concatentate_sigma_error_to_sim_data"
  - "concatenate_magnitudes_to_sim_data"
  - "concatenate_j_to_sim_data"

#global model network:
global_model:
  dropout: 0.1
  summary_dim: 64
  num_heads: 2

#local model network:
local_model:
  dropout: 0.1
  summary_dim: 16

hydra:
  run:
    dir: ${base_dir}/${results_dir}
